---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
        language_version: python3.8
        stages: [commit, push]

      - id: trailing-whitespace
        language_version: python3.8
        args: [--markdown-linebreak-ext=md]
        stages: [commit, push]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        language_version: python3.8
        stages: [commit, push]

  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8
        args: [--line-length=100]
        stages: [commit, push]

  # # Lint Python and Pass/Fail
  # - repo: https://github.com/PyCQA/pydocstyle
  #   rev: 4.0.1
  #   hooks:
  #     - id: pydocstyle
  #       language_version: python3.8
  #       stages: [commit, push]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-byte-order-marker
        language_version: python3.8
        stages: [commit, push]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        language_version: python3.8
        stages: [commit, push]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.740
  #   hooks:
  #     - id: mypy
  #       language_version: python3.8
  #       stages: [commit, push]  # Other Linters

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.18.0
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: {max: 120}}}"]
        stages: [commit, push]

#  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
#    rev: v0.1.0
#    hooks:
#      - id: dockerfilelint
#        stages: [commit, push]
...
